### ISSUE TITLE
Doesn't work for first time deploys

### ISSUE THREAD

**Issue by ryanto** [he9qi/ember-cli-deploy-fastboot-s3#11]
Hello!

It looks like a recent change in #9 breaks first time deploys. This line fails https://github.com/he9qi/ember-cli-deploy-fastboot-s3/blob/master/index.js#L136 because the deployInfo has not yet been uploaded.

cc @jheth

```
       |  +- fastboot-s3
       |    - preparing to activate f8a03a2c01e22c297830af7558808cfa
       |    - NoSuchKey: The specified key does not exist.
       |    - NoSuchKey: The specified key does not exist.
```

**Comment by jheth** [comment]
@ryanto Thanks for pointing that out. I'll get a fix put up for that.
