### ISSUE TITLE
Revision activation

### ISSUE THREAD

**Issue by willviles** [he9qi/ember-cli-deploy-fastboot-s3#3]
It'd be nice to enable [revision activation](https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index#what-does-activation-do) using the same pattern as [Ember CLI Deploy S3 Index](https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index).

- Use [Ember CLI Deploy Display Revisions](https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions) to find the revision key in the CLI.
- Activate the desired revision via `ember deploy:activate --revision <revision_key>`.

#### References
- [ember-cli-deploy-s3-index/index.js](https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/index.js)
- [ember-cli-deploy-s3-index/lib/s3.js](https://github.com/ember-cli-deploy/ember-cli-deploy-s3-index/blob/master/lib/s3.js)

**Comment by cspanring** [comment]
We are heavily using `revision` preview links in our workflow, meaning we are constantly deploying, but not activating, our app (for manual QA, etc.).

I believe with Fastboot we can't entirely keep that workflow, as you can't temporarily run a different server app just by using a revision query param. At least it doesn't sound like a trivial problem from my perspective.

A solution we are thinking of is to skip Fastboot for revisions, e.g. when the server route sees a `revision` query param, it just serves the SPA, never the SSR app. That would mean that the `deployInfo` file is only modified as part of the `activation` process, and not during `upload`.

The change to the addon seems reasonable: moving the execution of [_uploadDeployInfo](https://github.com/he9qi/ember-cli-deploy-fastboot-s3/blob/master/index.js#L61) from the `upload` to the `activation` hook.

@he9qi what do you think? I could take a stab at it and submit a PR for it.

**Comment by willviles** [comment]
@cspanring moving _uploadDeployInfo from the `upload` to the `activation` hook is definitely a requisite of adding revision activation!

I've not actually considered the use case of revision preview links. I assume you mean something like [this](https://dockyard.com/blog/2016/02/03/ember-cli-deploy-revision-previews), right? Sounds like a good issue to post on [Fastboot App Server](https://github.com/ember-fastboot/fastboot-app-server) to see if anyone has some insight there!

**Comment by cspanring** [comment]
@willviles we are using a slightly different approach, `?revision=1234` query param instead of url path, but it produces the same result.

**Comment by he9qi** [comment]
@willviles right! Revision preview links and switching between SPA and SSR is not something for this plugin.  

@cspanring  sure, feel free to do it!  :) It would be nice to be able to activate revisions.

and yes, adding revision query param into Fastboot doesn't look trivial, and it is not necessary I think. I mean preview links are only for internal use, right?  So completely agree with 

> ... skip Fastboot for revisions, e.g. when the server route sees a revision query param, it just serves the SPA, never the SSR app.

**Comment by cspanring** [comment]
@he9qi sounds good, will probably get to it tomorrow.

I was looking a little through Fastboot App Server, and I think the way to go would be plugging in custom middleware layers to handle revision links (and skip SSR for those cases, as they are only for internal use anyways).

**Comment by he9qi** [comment]
😄 cool!
